#pragma once

#define ZAWARTOSC_STAN_PUSTY 'p'
#define ZAWARTOSC_STAN_OPERAND 'd'
#define ZAWARTOSC_STAN_OPERACJA 'j'

//StakONP
#define BRAK_OPERACJI ';'
#define RODZAJ_OPERACJA 1
#define RODZAJ_OPERAND 2
#define RODZAJ_PUSTY 0

//Wczytywanie inputu
#define WCZYTAJ_TOKEN_KONIEC 0
#define WCZYTAJ_TOKEN_INT 1
#define WCZYTAJ_TOKEN_CHAR 2
#define WCZYTAJ_TOKEN_NAWIAS_OTW 3
#define WCZYTAJ_TOKEN_NAWIAS_ZAM 4
#define WCZYTAJ_TOKEN_PRZECINEK 5
#define WCZYTAJ_TOKEN_OPERACJA_ARGUMENTOWA 6
